package it.polimi.ingsw.client.gui;

/**
 * Enum that contains the list of possible game phases
 */
public enum GamePhases {

    INITIALIZATION,
    NICKNAME,
    NUMBEROFPLAYERS,
    WAITINGOTHERPLAYERS,
    INITIALLEADERCARDSELECTION,
    INITIALRESOURCESELECTION,
    MYTURN,
    OTHERPLAYERSTURN,
    BUYFROMMARKET,
    STORERESOURCES,
    ASKACTIVELEADER,
    ASKACTIVEPRODUCTION,
    LEADERPRODUCTION,
    BUYEVOLUTIONCARD,
    PRODUCTIONZONECHOICE,
    ENDGAME,
    CHOOSEWHITEBALL,
    SEEOTHERVIEW,

}
