package it.polimi.ingsw.client.GUI;

import it.polimi.ingsw.client.GUI.GUI;


public enum GamePhases {

    INITIALIZATION,
    NICKNAME,
    NUMBEROFPLAYERS,
    WAITINGOTHERPLAYERS,
    INITIALLEADERCARDSELECTION,
    INITIALRESOURCESELECTION,
    MYTURN,
    OTHERPLAYERSTURN,
    BUYFROMMARKET,
    STORERESOURCES,
    ASKACTIVELEADER,
    ASKACTIVEPRODUCTION,
    LEADERPRODUCTION,
    BUYEVOLUTIONCARD,
    PRODUCTIONZONECHOICE,
    ENDGAME,
    CHOOSEWHITEBALL,
    SEEOTHERVIEW,

}
