package it.polimi.ingsw.client;

public enum GamePhases {

    IINITIALIZATION,
    NICKNAME,
    NUMBEROFPLAYERS,
    WAITINGOTHERPLAYERS,
    INITIALLEADERCARDSELECTION,
    INITIALRESOURCESELECTION,
    MYTURN,
    OTHERPLAYERSTURN,
    STARTGAME,

    BUYFROMMARKET,
    STORERESOURCES,
    ASKACTIVELEADER,
    ASKACTIVEPRODUCTION,
    LEADERPRODUCTION,
    BUYEVOLUTIONCARD,
    PRODUCTIONZONECHOICE,
    ENDGAME,
}
