package it.polimi.ingsw.client;

public enum GamePhases {

    IINITIALIZATION,
    NICKNAME,
    NUMBEROFPLAYERS,
    WAITINGOTHERPLAYERS,
    INITIALLEADERCARDSELECTION,
    INITIALRESOURCESELECTION,
    MYTOURN,
    OTHERPLAYERSTOURN,
    STARTGAME
}
